### ISSUE TITLE
python version in readme update. 

### ISSUE THREAD

**Issue by TontonTremblay** [google-research/sparf#15]
Maybe update the python version to 3.10 instead of 3. Copy pasting your instruction give a non compatible python version with the requirements.txt.

**Comment by TontonTremblay** [comment]
I ended up using 3.10, it is installing all the packages correctly.

**Comment by TontonTremblay** [comment]
Also problems with your numpy version. 

```
(sparf-env) kinova@kinova:~/john/sparf$ python third_party/test_pdcnet_installation.py
/home/kinova/john/sparf/third_party/../third_party/DenseMatching
Did not load moviepy
Applying PDC-Net to two images of DTU...
Model: PDCNet
Pre-trained-model: megadepth
GOCor: Local iter 3
GOCor: Global iter 3
/home/kinova/miniconda3/envs/sparf-env/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/kinova/miniconda3/envs/sparf-env/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
/home/kinova/miniconda3/envs/sparf-env/lib/python3.10/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,
Traceback (most recent call last):
  File "/home/kinova/john/sparf/third_party/test_pdcnet_installation.py", line 127, in <module>
    test_model_on_image_pair(args, query_image, reference_image)
  File "/home/kinova/john/sparf/third_party/test_pdcnet_installation.py", line 83, in test_model_on_image_pair
    confident_warped = overlay_semantic_mask(warped_query_image, ann=255 - confident_mask*255, color=color)
  File "/home/kinova/john/sparf/third_party/../third_party/DenseMatching/utils_flow/visualization_utils.py", line 154, in overlay_semantic_mask
    im, ann = np.asarray(im, dtype=np.uint8), np.asarray(ann, dtype=np.int)
  File "/home/kinova/miniconda3/envs/sparf-env/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'inf'?
```
