### ISSUE TITLE
train stuck bug

### ISSUE THREAD

**Issue by lagrange10** [google-research/sparf#4]
Thanks for your excellent work.
During training, I encountered a persistent bug. While attempting to train using my own LLFF dataset, I consistently encountered the following error at step 5000 (I tried twice, and both times it happened exactly at step 5000). I'm new to this and unsure why it gets stuck at the line with "torch.cat". Has anyone else experienced a similar error?
```
[2023-06-10 18:39:08] [INFO] [Train] Iter: 4900/100000, error_R_before_align: 9.809, error_t_before_align: 0.488, error_R: 8.943, error_t: 0.227, loss_render: 0.011, loss_corres: 1.422, loss_render_matches: 0.000, loss_render_after_w: 0.011, loss_corres_after_w: 0.001, lr: 0.000894, cf_pe_progress: 0.048, PSNR: 19.422, lr_pose: 0.002, avg_pred_depth: 3.968, loss: 0.013, loss_depth_cons: 0.013, loss_depth_cons_after_w: 0.000013, perc_valid_corr_mask: 0.676, depth_in_corr_loss: 4.976, nbr_px_sampling: 2048.000, avg_vis_weight: 0.514, lr: 8.933e-04, time: 0.100s/0.418s
[2023-06-10 18:40:11] [INFO] [Train] Iter: 5000/100000, error_R_before_align: 9.754, error_t_before_align: 0.491, error_R: 8.962, error_t: 0.227, loss_render: 0.011, loss_corres: 1.326, loss_render_matches: 0.000, loss_render_after_w: 0.011, loss_corres_after_w: 0.001, lr: 0.000892, cf_pe_progress: 0.049, PSNR: 19.565, lr_pose: 0.002, avg_pred_depth: 3.948, loss: 0.012, loss_depth_cons: 0.012, loss_depth_cons_after_w: 0.000012, perc_valid_corr_mask: 0.669, depth_in_corr_loss: 4.948, nbr_px_sampling: 2048.000, avg_vis_weight: 0.515, lr: 8.913e-04, time: 0.100s/0.420s
^CTraceback (most recent call last):
  File "/nfs/gitdownload/sparf/run_trainval.py", line 156, in <module>
    main()
  File "/nfs/gitdownload/sparf/run_trainval.py", line 151, in main
    run_training(args.train_module, args.train_name, cudnn_benchmark=args.cudnn_benchmark, seed=args.seed,
  File "/nfs/gitdownload/sparf/run_trainval.py", line 112, in run_training
    trainer.run(load_latest=True)
  File "/nfs/gitdownload/sparf/source/training/base.py", line 400, in run
    self.inference()
  File "/home/chentao/miniconda3/envs/sparf/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/nfs/gitdownload/sparf/source/training/joint_pose_nerf_trainer.py", line 563, in inference
    super().inference()
  File "/home/chentao/miniconda3/envs/sparf/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/nfs/gitdownload/sparf/source/training/engine/iter_based_trainer.py", line 194, in inference
    output_dict, result_dict, plotting_dict = self.val_step(iteration, data_dict)
  File "/home/chentao/miniconda3/envs/sparf/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/nfs/gitdownload/sparf/source/training/base.py", line 457, in val_step
    output_dict = self.net.forward(self.settings,data_dict,mode="val",iter=self.iteration)  
  File "/nfs/gitdownload/sparf/source/models/renderer.py", line 133, in forward
    ret = self.render_by_slices(opt,pose,intr=data_dict.intr,mode=mode, 
  File "/nfs/gitdownload/sparf/source/models/renderer.py", line 381, in render_by_slices
    ret = self.render(opt,pose,H=H, W=W, intr=intr,ray_idx=ray_idx,depth_range=depth_range, iter=iter, mode=mode) # [B,R,3],[B,R,1]
  File "/nfs/gitdownload/sparf/source/models/renderer.py", line 281, in render
    center,ray = camera.get_center_and_ray(pose, H, W,intr=intr) # [B,HW,3]
  File "/nfs/gitdownload/sparf/source/utils/camera.py", line 376, in get_center_and_ray
    center_3D = cam2world(center_3D,pose_w2c) # [B,HW,3]  
  File "/nfs/gitdownload/sparf/source/utils/camera.py", line 332, in cam2world
    pose_c2w = Pose().invert(pose_w2c)
  File "/nfs/gitdownload/sparf/source/utils/camera.py", line 97, in invert
    pose_inv = self(R=R_inv,t=t_inv)
  File "/nfs/gitdownload/sparf/source/utils/camera.py", line 88, in __call__
    pose = torch.cat([R,t[...,None]],dim=-1) # [...,3,4]
KeyboardInterrupt
```

# the third try: set max iters = 4999 and stuck in 4900
```
  File "/nfs/gitdownload/sparf/source/models/renderer.py", line 133, in forward
    ret = self.render_by_slices(opt,pose,intr=data_dict.intr,mode=mode, 
  File "/nfs/gitdownload/sparf/source/models/renderer.py", line 381, in render_by_slices
    ret = self.render(opt,pose,H=H, W=W, intr=intr,ray_idx=ray_idx,depth_range=depth_range, iter=iter, mode=mode) # [B,R,3],[B,R,1]
  File "/nfs/gitdownload/sparf/source/models/renderer.py", line 281, in render
    center,ray = camera.get_center_and_ray(pose, H, W,intr=intr) # [B,HW,3]
  File "/nfs/gitdownload/sparf/source/utils/camera.py", line 371, in get_center_and_ray
    xy_grid = xy_grid.repeat(batch_size,1,1) # [B,HW,2]
KeyboardInterrupt
```

**Comment by lagrange10** [comment]
I am honored to receive a response from the author. Thank you for the insights you provided. Although they are simple suggestions, they have been very helpful for me as a beginner. I have already tried training on the fern dataset and it works successfully. It seems that the issue may lie with my custom dataset, even though these datasets work fine in other NeRF projects.

> Hi, I myself have not encountered this issue. Did you try running the training on the original dataset and train splits and could you reproduce the results? That would be a good starting point to understand what is happening.

**Comment by lagrange10** [comment]
> I am honored to receive a response from the author. Thank you for the insights you provided. Although they are simple suggestions, they have been very helpful for me as a beginner. I have already tried training on the fern dataset and it works successfully. It seems that the issue may lie with my custom dataset, even though these datasets work fine in other NeRF projects.
> 
> > Hi, I myself have not encountered this issue. Did you try running the training on the original dataset and train splits and could you reproduce the results? That would be a good starting point to understand what is happening.

I have resolved the issue, and it appears to be related to a specific scene. I tested it with another custom scene, and it performed well. Therefore, there might be no need to reproduce the problem unless this bug consistently appears. Thanks to your advice.
